services:
  stanchev-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nginx-network
    depends_on:
      - stanchev-db
    expose:
      - "9000"

  stanchev-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-metalworking}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${DB_USERNAME:-metalworking}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - stanchev-metalworking-mysql-data:/var/lib/mysql
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true

volumes:
  stanchev-metalworking-mysql-data:
    driver: local